### ISSUE TITLE
Which bootloader/layout are you using on your GL.iNet GL-MT6000

### ISSUE THREAD

**Issue by graysky2** [Fail-Safe/Fail-Safe#1]
I ordered one of these and am wondering which bootloader you're using on yours...

According to the [wiki](https://openwrt.org/toh/gl.inet/gl-mt6000):
>Use an OpenWrt sysupgrade image for the initial install. It is compatible with the OEM webUI flashing routine and retains the OEM recovery which includes a webUI. (Installing the OpenWrt factory image would also flash the OpenWrt version of the u-boot bootloader which would make recovery more difficult.)

I would think that OpenWrt's version of u-boot would be better than whatever the OEM fork provides.

**Comment by Fail-Safe** [comment]
Howdy! I stuck with the OEM bootloader. It was one of those "if it ain't broke, don't fix it" kind of decisions for me. It works perfectly well for me and has already saved my butt a few times I was trying to initially get my MT6000 custom image bootable. I didn't want to have to deal with opening the unit to do anything UART, so having the OEM webUI is pretty handy.

**Comment by graysky2** [comment]
OK, thanks.

**Comment by graysky2** [comment]
@Fail-Safe  -  Do you mind taking a look at a thread I created: https://forum.openwrt.org/t/glinet-mt6000-flashed-to-opwnwrt-snapshot-but-seems-to-be-read-only/191691  Have you experienced this?
